### PR TITLE
Merge Athan branch

### PR DESCRIPTION
**Pull request by ebraminio**

### CODE REVIEW

**Comment by hamidsafdari** [comment]
To do anything that uses the alarm and sets a timer to trigger something at a specified time, you have to use the WAKE_LOCK permission. There's no advantage to it. This is how android works.

**Comment by hamidsafdari** [comment]
@ebraminio, you said you didn't want the Athan sound preference, this branch doesn't still have that. Do you want it to be included?

**Comment by ebraminio** [comment]
If adding that preference would need the permission I'd rather to not have that. Please add the commit to remove unnecessary permissions and make sure this branch is stable and ready to merge and has all the missed change due my fault on backwarding the history on the master. Thank you

**Comment by ebraminio** [comment]
@hamidsafdari: Can you please fix the merge conflict issue here? I plan to immediately merge this afterward. Thank you

**Comment by ebraminio** [comment]
Please note that some of your commits are already on the master so I'd guess that would not be hard

**Pull request merged**
